---
- name: (Debian/Red Hat/SLES OSs) Set up Envoy Proxy signing key URL
  set_fact:
    keysite: "{{ envoyproxy_signing_key | default(envoyproxy_default_signing_key_pgp) }}"
  when: ansible_facts['os_family'] != "Alpine"

- name: (Debian/Ubuntu) Add Envoy Proxy signing key
  apt_key:
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    url: "{{ keysite }}"
  when: ansible_facts['os_family'] == "Debian"

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL/SLES) Add Envoy Proxy signing key
  rpm_key:
    fingerprint: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    key: "{{ keysite }}"
    validate_certs: "{{ (ansible_facts['distribution_major_version'] is version('6', '==')) | ternary('no', 'yes') }}"
  when: ansible_facts['os_family'] in ['RedHat', 'Suse']
