---
- name: (Debian/Red Hat/SLES OSs) Set up Envoy Proxy signing key URL
  set_fact:
    keysite: "{{ envoyproxy_signing_key | default(envoyproxy_default_signing_key_pgp[ansible_facts['os_family'] | lower]) }}"
  when: ansible_facts['os_family'] != "Alpine"

- name: (Debian/Ubuntu) Add Envoy Proxy signing key
  apt_key:
    url: "{{ keysite }}"
  when: ansible_facts['os_family'] == "Debian"

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL/SLES) Add Envoy Proxy signing key
  rpm_key:
    key: "{{ keysite }}"
  when: ansible_facts['os_family'] in ['RedHat', 'Suse']
