---
- name: Create override directory for envoyproxy systemd service
  file:
    path: "{{ envoyproxy_service_overridepath }}"
    state: directory
    mode: 0755

- name: Create override for envoyproxy systemd service
  template:
    src: "{{ role_path }}/templates/services/envoyproxy.service.override.conf.j2"
    dest: "{{ envoyproxy_service_overridepath }}/{{ envoyproxy_service_overridefilename }}"
    owner: root
    group: root
    mode: 0644
  when:
    - not envoyproxy_service_custom | bool
    - not envoyproxy_service_clean | bool
  notify: (Handler) Systemd daemon-reload

- name: Customize override for envoyproxy systemd service
  copy:
    src: "{{ envoyproxy_service_custom_file }}"
    dest: "{{ envoyproxy_service_overridepath }}/{{ envoyproxy_service_overridefilename }}"
    owner: root
    group: root
    mode: 0644
  when:
    - envoyproxy_service_custom | bool
    - not envoyproxy_service_clean | bool
  notify: (Handler) Systemd daemon-reload

- name: Remove override for envoyproxy systemd service
  file:
    path: "{{ envoyproxy_service_overridepath }}"
    state: absent
  when: envoyproxy_service_clean | bool
  notify: (Handler) Systemd daemon-reload
