---
- name: "Create envoy directory"
  file:
    path: "{{ envoyproxy_config_path }}"
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: "Create envoy log directory"
  file:
    path: "{{ envoyproxy_log_path }}"
    state: directory
    owner: root
    group: root
    mode: "0777" # Improve this in the future, as it's bad

- name: Copy templates to default directory
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
    #validate: envoy --mode validate --config-path %s
  loop:
    - { src: envoy.yaml.j2, dest: "{{ envoyproxy_config_path }}/{{ envoyproxy_config_name }}" }
  notify: (Handler) Run Envoy Proxy
