---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-envoyproxy"
      include_role:
        name: "ansible-role-envoyproxy"
      vars:
        envoyproxy_enable: true
        envoyproxy_start: true
        envoyproxy_install: true
        envoyproxy_state: present
        envoyproxy_config_path: /etc/envoy
        envoyproxy_config_name: envoy.yaml
        envoyproxy_install_from: envoyproxy_repository
        envoyproxy_debug_output: true
        envoyproxy_logrotate_conf_enable: true
        envoyproxy_logrotate_conf:
          paths:
            - "/var/log/envoyproxy/*.log"
          options:
            - daily
            - missingok
            - rotate 14
            - compress
            - delaycompress
            - notifempty
            - create 0644 root adm  # Changes envoyproxy logs permissions
            - sharedscripts
        nodes:
          - 127.0.0.1
          - 8.8.8.8
