---
- name: (Debian) Install dependencies
  apt:
    name: "{{ envoyproxy_debian_dependencies }}"
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: (Ubuntu) Install dependencies
  apt:
    name: "{{ envoyproxy_ubuntu_dependencies }}"
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: (CentOS/RHEL) Install dependencies
  yum:
    name: "{{ envoyproxy_redhat_dependencies }}"
  when: ansible_facts['os_family'] == "RedHat"
