---
- name: Install Envoy Proxy in Linux systems
  block:
    - name: Install Envoy Proxy from repository
      include_tasks: "{{ role_path }}/tasks/opensource/install-{{ ansible_facts['os_family'] | lower }}.yml"
      when: envoyproxy_install_from == "envoyproxy_repository"

    - name: Install Envoy Proxy from source
      include_tasks: "{{ role_path }}/tasks/opensource/install-source.yml"
      when: envoyproxy_install_from == "source"

    - name: Install Envoy Proxy from package
      package:
        name: "envoyproxy{{ envoyproxy_version | default('') }}"
        state: "{{ envoyproxy_state }}"
      when: envoyproxy_install_from == "os_repository"
      notify: (Handler) Run Envoy Proxy
  when: ansible_facts['system']
