---
- name: "Create Envoy Proxy config directory"
  file:
    path: "{{ envoyproxy_config_path }}"
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Copy templates to default location
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - { src: services/docker-compose.yml.j2, dest: "{{ envoyproxy_config_path }}/docker-compose.yml" }