---
name: Ansible Galaxy import
on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: 'hugoprudente.envoyproxy'

jobs:
  galaxy:
    name: Galaxy
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: 'hugoprudente.envoyproxy'

      - name: Set up Python 3
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip3 install -r .github/workflows/requirements/requirements_galaxy.txt

      - name: Import release to Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
