---
name: Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    ignore-tags:
      - "*"
  schedule:
    - cron: "0 2 15 * *"

defaults:
  run:
    working-directory: 'hugoprudente.envoyproxy'

jobs:
  integration:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scenario:
          - default
          - container
        distro:
          - centos8
          - ubuntu2004
          - debian10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: hugoprudente.envoyproxy

      - name: Set up Python 3.
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9

      - name: Install test dependencies.
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Uninstall Ansible community distribution (temporary)
        run: pip3 uninstall -y ansible
      
      - name: Install Ansible base dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_ansible.yml --force

      - name: Run Molecule test
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
