---
name: Integration
on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: "0 5 * * 4"

defaults:
  run:
    working-directory: 'hugoprudente.envoyproxy'

jobs:
  integration:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro:
          - centos8
          - ubuntu2004
          #- debian10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: hugoprudente.envoyproxy

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies.
        run: pip3 install flake8 yamllint ansible molecule[docker] docker ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}