---
name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    ignore-tags:
      - "*"
  schedule:
    - cron: "0 5 * * 4"

defaults:
  run:
    working-directory: 'hugoprudente.envoyproxy'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: hugoprudente.envoyproxy

      - name: Set up Python 3.
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.9

      - name: Install test dependencies.
        run: pip3 install -r .github/workflows/requirements/requirements_lint.txt

      - name: Lint code.
        run: |
          yamllint -c .yamllint .
          ansible-lint